### ISSUE TITLE
"List" Example Code

### ISSUE THREAD

**Issue by MRMTC** [esnet/react-dynamic-forms#40]
Hi Guys,

Firstly, thanks for the great library, its really helping me out on a project that I'm working on.  I wanted to generate a form where one can add/remove items depending on a "fixed count".  To do this, I wanted to use the example described here: http://software.es.net/react-dynamic-forms/#/example/list

However, I can't seem to get the code to "compile" on my end - I think I'm missing how to link the two "items" listed on the page which are the "email address/type" to the rest of the form to edit the contact. 
 The two constant expressions at the end of the first coded snippet confused me on my end:
const EmailList = formList(EmailForm);
const Emails = formGroup(EmailList);

Do you perhaps have a "code example" for the example listed on the page ( http://software.es.net/react-dynamic-forms/#/example/list)?  Please forgive me if I have missed it here somewhere on your  #repo.

Thanks.

**Comment by pjm17971** [comment]
Better late than never, in case someone else is looking for example source, it's in this repo, under packages/website, for example:
https://github.com/esnet/react-dynamic-forms/tree/master/packages/website/src/examples/list

**Comment by MRMTC** [comment]
Noted, thanks @pjm17971 :)
